print('SetDefault')
self.checkBox_8.setChecked(True)
self.checkBox_9.setChecked(False)
self.checkBox_10.setChecked(True)
self.checkBox_11.setChecked(True)
self.checkBox_12.setChecked(True)
self.checkBox_13.setChecked(True)
self.checkBox_14.setChecked(True)
self.checkBox_15.setChecked(False)
self.checkBox_16.setChecked(True)
self.checkBox_17.setChecked(True)
self.checkBox_18.setChecked(True)
self.checkBox_19.setChecked(True)

